<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEkntrSL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEkntrSL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEkntrSL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEkntrSL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEkntrSL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EkntrSL',
    'container.build_id' => 'dd319403',
    'container.build_time' => 1576534967,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEkntrSL');
