<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Zos1TBe' shared service.

return $this->privates['.service_locator.Zos1TBe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'temoignage' => ['privates', '.errored..service_locator.Zos1TBe.App\\Entity\\Temoignage', NULL, 'Cannot autowire service ".service_locator.Zos1TBe": it references class "App\\Entity\\Temoignage" but no such service exists.'],
], [
    'manager' => '?',
    'temoignage' => 'App\\Entity\\Temoignage',
]);
