<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Rvbpldd' shared service.

return $this->privates['.service_locator.Rvbpldd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'tarif' => ['privates', '.errored..service_locator.Rvbpldd.App\\Entity\\Tarif', NULL, 'Cannot autowire service ".service_locator.Rvbpldd": it references class "App\\Entity\\Tarif" but no such service exists.'],
], [
    'tarif' => 'App\\Entity\\Tarif',
]);
