<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.q0D7zTM' shared service.

return $this->privates['.service_locator.q0D7zTM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'image' => ['privates', '.errored..service_locator.q0D7zTM.App\\Entity\\Images', NULL, 'Cannot autowire service ".service_locator.q0D7zTM": it references class "App\\Entity\\Images" but no such service exists.'],
], [
    'image' => 'App\\Entity\\Images',
]);
