<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GwFBfCO' shared service.

return $this->privates['.service_locator.GwFBfCO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'aboutme' => ['privates', '.errored..service_locator.GwFBfCO.App\\Entity\\Aboutme', NULL, 'Cannot autowire service ".service_locator.GwFBfCO": it references class "App\\Entity\\Aboutme" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
], [
    'aboutme' => 'App\\Entity\\Aboutme',
    'manager' => '?',
]);
