<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VMCCGfk' shared service.

return $this->privates['.service_locator.VMCCGfk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'aboutme' => ['privates', '.errored..service_locator.VMCCGfk.App\\Entity\\Aboutme', NULL, 'Cannot autowire service ".service_locator.VMCCGfk": it references class "App\\Entity\\Aboutme" but no such service exists.'],
], [
    'aboutme' => 'App\\Entity\\Aboutme',
]);
