<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PY50zup' shared service.

return $this->privates['.service_locator.PY50zup'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'aboutmeRepository' => ['privates', 'App\\Repository\\AboutmeRepository', 'getAboutmeRepositoryService.php', true],
], [
    'aboutmeRepository' => 'App\\Repository\\AboutmeRepository',
]);
