<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9c5qMYo' shared service.

return $this->privates['.service_locator.9c5qMYo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'imagesRepository' => ['privates', 'App\\Repository\\ImagesRepository', 'getImagesRepositoryService.php', true],
], [
    'imagesRepository' => 'App\\Repository\\ImagesRepository',
]);
