<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UMqOL3Y' shared service.

return $this->privates['.service_locator.UMqOL3Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'temoignage' => ['privates', '.errored..service_locator.UMqOL3Y.App\\Entity\\Temoignage', NULL, 'Cannot autowire service ".service_locator.UMqOL3Y": it references class "App\\Entity\\Temoignage" but no such service exists.'],
], [
    'temoignage' => 'App\\Entity\\Temoignage',
]);
