<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ivb9eL0' shared service.

return $this->privates['.service_locator.ivb9eL0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'temoignageRepository' => ['privates', 'App\\Repository\\TemoignageRepository', 'getTemoignageRepositoryService.php', true],
], [
    'temoignageRepository' => 'App\\Repository\\TemoignageRepository',
]);
